name: Run schema validation
on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }} && ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  schema-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: 'true'

      - name: Read Node version from .nvmrc
        id: node_version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Install dependencies
        run: npm ci

      #      This workflow exists so we do not have to locally generate the OpenAPI spec.
      #      If the OpenAPI spec was changed, it commits and pushes those changes back to the PR branch.
      - name: Generate OpenAPI docs from code
        run: npm run generate:openapi

      - name: Check if OpenAPI docs have changed
        id: check_changes
        run: |
          if git diff --quiet src/api-docs/openapi.yml src/api-docs/openapi.json; then
            echo "changes=false" >> $GITHUB_ENV
          else
            echo "changes=true" >> $GITHUB_ENV
          fi

      - name: Commit and push OpenAPI changes
        if: env.changes == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHubActions'
          author_email: 'actions@github.com'
          message: 'Update OpenAPI spec'
          add: 'src/api-docs/openapi.yml src/api-docs/openapi.json'
          push: 'true'
#          github_token: '${{ github.GITHUB_TOKEN }}'
          github_token: '${{ github.GITHUB_PERSONAL_TOKEN }}'

      - name: Create empty commit to re-run checks
        if: env.changes == 'true'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit --allow-empty -m "Re-run checks after OpenAPI update"
          git push origin HEAD:${{ github.head_ref }}

      - name: Fetch main branch for Optic
        run: git fetch --depth=1 origin main:main

      - name: Optic diff
        run: npm run optic:diff